repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.3'
    hooks:
    - id: flake8
      language_version: python3.6.9

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: debug-statements
